groups:
- group: 0x09
  allow_undefined: [0x64, 0x65, 0x66, 0x67, 0x68, 0x69, 0x6a, 0x6b, 0x6c, 0x6d]
  data:
  - name: TX_09_MESSAGE_SPEED
    index: 0x6e
    text: |-
      Message Speed
      How quickly text appears.
      Speed 8 is instantaneous.

  - name: TX_09_PASSIVE_SHIELD
    index: 0x6f
    text: |-
      Passive Shield
      Shield is passively
      held at all times.

  - name: TX_09_DUNGEON_AUTOSAVE
    index: 0x70
    text: |-
      Dungeon Autosave
      Game is saved
      upon entering or
      exiting a dungeon.

  - name: TX_09_BRACELET_PUNCH
    index: 0x71
    text: |-
      Bracelet Punch
      Bracelet usage
      becomes punch if
      nothing grabbable
      (requires ring).

  - name: TX_09_CONTEXT_SENSITIVE_ITEMS_0
    index: 0x72
    text: |-
      Sword & Bracelet
      Sword/Bracelet is
      auto-equipped when
      touching a cuttable
      or liftable block.

  - name: TX_09_CONTEXT_SENSITIVE_ITEMS_1
    index: 0x73
    text: |-
      Seeds & Shovel
      Ember Seeds/Shovel is
      auto-equipped when
      touching a burnable
      or diggable block.

  - name: TX_09_CONTEXT_SENSITIVE_ITEMS_2
    index: 0x74
    text: |-
      Rod & Harp
      Rod/Harp is
      auto-equipped if
      standing on a stump
      or a time portal.

  - name: TX_09_CONTEXT_SENSITIVE_BUTTON
    index: 0x75
    text: |-
      Context Button
      The button that all
      contextual items
      are equipped to.

  - name: TX_09_LOW_HEART_WARNING
    index: 0x76
    text: |-
      Low-Heart Beep
      A warning sound will play
      while you are at 1/4 or
      less of your max health.

  - name: TX_09_QUICK_SWAP
    index: 0x77
    text: |-
      Quick Swapping
      Hold Select to swap
      \abtn/\bbtn items with
      the first two inventory
      items. Release without
      pressing \abtn/\bbtn to
      open the map.

  - name: TX_09_QUICK_DROP
    index: 0x78
    text: |-
      Quick Drop/Throw
      Continue to hold
      \abtn/\bbtn after lifting
      something to instantly
      drop it. Moving will
      instead throw it.

  - name: TX_09_CARTRIDGE_RUMBLE
    index: 0x79
    text: |-
      Cartridge Rumble
      Enables rumble
      when taking damage.
      Requires the cartridge
      have rumble support.